language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
 - "java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &"
script:
 - PYTHONPATH='.' python -m test_examples/unittest_example/tests
 - PYTHONPATH='.' lettuce test_examples/lettuce_example/
 - PYTHONPATH='.' py.test -v test_examples/pytest_example/tests.py
