language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
script:
 - python test_examples/unittest_example/tests.py
 - lettuce test_examples/lettuce_example/
 - py.test -v test_examples/pytest_example/tests.py
