language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
 - PYTHONPATH='.' python -m test_examples/unittest_example/tests
 - PYTHONPATH='.' lettuce test_examples/lettuce_example/
 - PYTHONPATH='.' py.test -v test_examples/pytest_example/tests.py
