language: python
dist: bionic
sudo: true
cache:
  pip: true
install: pip install -r requirements.txt
script: tox
deploy:
  - provider: pypi
    user: "__token__"
    # password: is defined via encrypted env var $PYPI_PASSWORD (stored on travis server)
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      repo: authomatic/liveandletdie

